name: CI Infra as Code
on:
  [workflow_dispatch, push]
concurrency: ci-${{ github.ref }}
jobs:

  trivy:
    name: Run Trivy (Iac and fs mode)
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      # Trivy scans Infrastructure as Code (IaC) Terraform, CloudFormation, Dockerfile and Kubernetes.
      - name: Run Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'table'
          exit-code: '1'
          ignore-unfixed: false
          severity: 'MEDIUM,HIGH,CRITICAL'

      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          hide-progress: false
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'MEDIUM,HIGH,CRITICAL'
  insecure-cf:
    name: Scan Insecure Cloudformation patterns
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Insecure Cloudformation patterns
        uses: stelligent/cfn_nag@master
        with:
          input_path: cfn
          extra_args: --fail-on-warnings

      - name: Fail if cfn_nag scan contains failures, warnings
        # sum cfn_nag failures, warnigns and return it as exit code
        run: |
          exit `grep -E '^(Failures|Warnings)' cfn_nag.out | awk '{ SUM += $3} END { print SUM }'`
